### ISSUE TITLE
能给个联系方式吗，有代码方面的问题想请教

### ISSUE THREAD

**Issue by zhyluocheng** [Do1e/NJU-nemu#1]
能给个联系方式吗，有代码方面的问题想请教

**Comment by Do1e** [comment]
邮件：Do1e@njuee.onmicrosoft.com

**Comment by Do1e** [comment]
> 能给个联系方式吗，有代码方面的问题想请教

邮件：[Do1e@njuee.onmicrosoft.com](mailto:Do1e@njuee.onmicrosoft.com)
